### ISSUE TITLE
vcf2fhir fails to install

### ISSUE THREAD

**Issue by mad-scientist-in-training** [elimuinformatics/vcf2fhir#107]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

Hi I'm attempting to get vcf2fhir installed, but keep running into issues. I have installed cython and wheel and checked that they are installed, but when I run pip install vcf2fhir I get persistent error messages. 

Are there more dependencies that might be the issue? Seems like it might be an issue with pysam, but wanted to confirm if you've seen folks encounter this error in the past and there's an different fix.. Please see the below error message that I keep getting, thanks. 

* Package Version: python 3.9.16
* Operating System: Windows 10, 64 bit OS

## Expected Behavior

Package to install. 

## Current Behavior

Failure to install

## Failure Information

Collecting vcf2fhir
  Using cached vcf2fhir-0.1.1-py3-none-any.whl (26 kB)
Collecting pyranges>=0.0.96
  Downloading pyranges-0.0.120.tar.gz (687 kB)
     ---------------------------------------- 687.9/687.9 kB 14.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pysam
  Using cached pysam-0.20.0.tar.gz (4.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\clake\AppData\Local\Temp\pip-install-y1s5vygs\pysam_f4fe7232d0f142c9b8aae5c716f0a979\setup.py", line 381, in <module>
          htslib_make_options = run_make_print_config()
        File "C:\Users\clake\AppData\Local\Temp\pip-install-y1s5vygs\pysam_f4fe7232d0f142c9b8aae5c716f0a979\setup.py", line 79, in run_make_print_config
          stdout = subprocess.check_output(["make", "-s", "print-config"])
        File "C:\Users\clake\Anaconda3\envs\test\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\clake\Anaconda3\envs\test\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\clake\Anaconda3\envs\test\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\clake\Anaconda3\envs\test\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      # pysam: htslib configure options: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by rhdolin** [comment]
Hi, can you please take a look at https://github.com/elimuinformatics/vcf2fhir/issues/70, and see if this is a similar issue? Are you able to test on a different platform?

**Comment by mad-scientist-in-training** [comment]
I got it to work, thank you!
