### ISSUE TITLE
Question: how to scale up vcf2fhir

### ISSUE THREAD

**Issue by mad-scientist-in-training** [elimuinformatics/vcf2fhir#108]
Hi I just had a quick question - I'm trying to run vcf2fhir on large vcfs, and the process is taking many hours - is there a way to scale up? I'm working on GCP so I can use whatever resources I need. 

Thanks, 

Camille

**Comment by rhdolin** [comment]
Camille, have you tried using a bgzipped VCF with a tabix index? Also, are you converting the entire file, and have you considered just converting key regions of interest?

**Comment by mad-scientist-in-training** [comment]
I would love to convert just key regions on interest - is there a streamlined process for picking those regions out and making a smaller VCF? 

Thanks, 

Camille

**Comment by rhdolin** [comment]
Hi Camille,

We provide some additional documentation here (https://vcf2fhir.readthedocs.io/en/latest/). You won't be making a smaller VCF, but rather, you'll selectively convert specified regions from the larger VCF.

You can limit the conversion region using a conversion region dictionary (e.g. conv_region_dict={"Chromosome": ["X", "X", "M"],"Start": [50000, 55000, 50000],"End": [52000, 60600, 60025]}) or a conversion region BED file (e.g. conv_region_filename="WGS_b37_convert_everything.bed").

Values for Chromosome must align with values in VCF #CHROM field. Ranges must be 0-based and based on GRCh37 or GRCh38 reference sequences. 

You'll find some sample BED files here https://github.com/elimuinformatics/vcf2fhir/tree/master/vcf2fhir/test

Either way, for very large files, I suspect the process will be more efficient with zipped and indexed VCF files.
