### ISSUE TITLE
Conform to HL7 find-subject-variants output

### ISSUE THREAD

**Issue by rhdolin** [elimuinformatics/vcf2fhir#14]
After the anticipated Jan 2021 ballot, we may need to update the output of this service to conform to the latest FHIR Genomics format.

**Comment by rhdolin** [comment]
@samreenjs Since creating this issue, the HL7 community is now thinking of revision the set of FHIR Genomics operations. An early draft is [here](https://docs.google.com/document/d/1DRbryf2-UYBHHm7TV3Pq87xZRGP6pvZQELhAiL_nyVY/edit). I think we should defer on this, until we have a clearer sense of direction in HL7. Are there other issues you might want to tackle?

**Comment by samreenjs** [comment]
Alright sir. I will try solving some other issue

**Comment by rhdolin** [comment]
we are deferring this one indefinitely, so will close for now
