### ISSUE TITLE
Shift the build process to PEP-517

### ISSUE THREAD

**Issue by rhdolin** [elimuinformatics/vcf2fhir#18]
Evaluate and change the build process to [PEP-517](https://www.python.org/dev/peps/pep-0517/)

**Comment by Arraxx** [comment]
I would like to work on this, can i take this up?

**Comment by srgothi92** [comment]
Sounds good. @rhdolin  Is it possible to assign this issue ?  We would like to avoid any wasted effort if someone else is working on this too.

**Comment by rhdolin** [comment]
Yes, let's assign to @Arraxx . Aman, thanks for taking this one on.

**Comment by Arraxx** [comment]
Thanks for assigning me this issue. i have started reading the PEP 517 documentation and will try to fix this ASAP.

**Comment by theanmolsharma** [comment]
@Arraxx Are you still working on this issue? If not can I take it from here?

**Comment by Arraxx** [comment]
Yes @theanmolsharma, I am still working on the issue. I'm relatively new to python and working on this issue will be a great if you find another issue. 
If I found myself unable to solve this issue I will mention you for the same.

**Comment by theanmolsharma** [comment]
@Arraxx Sure man, take your time.
