### ISSUE TITLE
Release a new version 0.0.17 with proper Changelog updates

### ISSUE THREAD

**Issue by srgothi92** [elimuinformatics/vcf2fhir#34]
After all the refactoring, cleanup and new tests we should release a new version.

Till now we have been releasing new versions but we never maintained a proper CHANGELOG.md file to list all the important changes that are made in this new release. We should start doing that and this release will be that first with Changelog.

**Comment by Rohan-cod** [comment]
That's a really great idea @srgothi92. It will make it easier for users to understand what has changed between releases, what will be introduced in the next release, which features became deprecated and which were entirely removed. 

Can I contribute to it in some way?
