### ISSUE TITLE
Remove 'Human reference sequence assembly version' component from variant observation

### ISSUE THREAD

**Issue by rhdolin** [elimuinformatics/vcf2fhir#36]
'Human reference sequence assembly version' can be inferred from RefSeq, and doesn't always apply (e.g. for mitochondrial refSeq's).

**Comment by rhdolin** [comment]
@theanmolsharma Begin by reading the [manual](https://github.com/elimuinformatics/vcf2fhir/blob/master/docs/Manual.md) to understand high-level how translation works. Then focus on '[create variant observations](https://github.com/elimuinformatics/vcf2fhir/blob/master/docs/Manual.md#create-variant-observations)' section. You'll see that each time the converter creates a FHIR Variant observation, that observation includes a component "LOINC 62374-4 'Human reference sequence assembly version' = GRCh37 or GRCh38, as determined from parameter value". You can see an example of this component by searching [this ](https://github.com/elimuinformatics/vcf2fhir/blob/master/vcf2fhir/test/expected_example4.json) example. 

The idea here is to modify the code so that we are no longer creating this component with a variant observation.

**Comment by theanmolsharma** [comment]
@rhdolin I think I got what I need to do, I will start working on it right away.

**Comment by rhdolin** [comment]
@theanmolsharma Take a look at lines 127-132 in fhir_helper.py to see where this component is getting added.

**Comment by theanmolsharma** [comment]
@rhdolin I removed the lines that generated that component.
