### ISSUE TITLE
Add support for multi-sample VCFs

### ISSUE THREAD

**Issue by rhdolin** [elimuinformatics/vcf2fhir#37]
Use the first sample in a multi-sample VCF. Test that a multi-sample VCF works correctly.

**Comment by samreenjs** [comment]
I would like to work on this issue. 
Sir, please assign this issue to me.

**Comment by rhdolin** [comment]
Thanks @samreenjs. Are you familiar with multi-sample VCFs? Let me know if you need some help getting started on this one.

**Comment by samreenjs** [comment]
Thanks for assigning me this issue. It would be great if you can provide me some resources and guidance that will help solve it.

**Comment by rhdolin** [comment]
@samreenjs If you look at the [VCF 4.3 spec](https://samtools.github.io/hts-specs/VCFv4.3.pdf), section 1.1 'An Example' shows a VCF with multiple samples (there is a sample for NA00001, NA00002, NA00003). We want to make sure the vcf2fhir code correctly processes such a file with multiple samples, by just converting the first sample (NA00001) and ignoring the other samples. So the task is to check the code to see if any enhancements are needed to support multi-sample VCFs, and probably also to add some test cases.

**Comment by rhdolin** [comment]
this issue had previously been addressed already
