### ISSUE TITLE
Meet the GitHub community checklist for public repository

### ISSUE THREAD

**Issue by srgothi92** [elimuinformatics/vcf2fhir#41]
According to GitHub [here](https://github.com/elimuinformatics/vcf2fhir/community), we still do not meet all the checklist for a public GitHub repository. We should complete the remaining checklist as part of this issue.

**Comment by Rohan-cod** [comment]
I would like to work on this issue. Can you please assign it to me.

**Comment by rhdolin** [comment]
@srgothi92 Ok, all done

**Comment by hankwallace** [comment]
all set now
![image](https://user-images.githubusercontent.com/3484543/114042467-75bd9b80-9853-11eb-9579-df5e68310d3a.png)
