### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by srgothi92** [elimuinformatics/vcf2fhir#49]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Context

Documentation Issue.

## Expected Behavior

Documentation should be correct

## Current Behavior

There were recent changes in `Converter` parameters, documentation should reflect examples of consuming new parameter.

**Comment by srgothi92** [comment]
I was specifically talking about newly added parameter [ratio_ad_dp](https://github.com/elimuinformatics/vcf2fhir/issues/49). However, this issue is not just for this parameter. We should consider updating any documentation nit both in are Readme and documentation site.

**Comment by abhishek-jain-1999** [comment]
@srgothi92 I want to work on this issue please tell how can I proceed

**Comment by srgothi92** [comment]
@abhishek-jain-1999 you can just make changes to the documentation and raise a PR. Do you need any additional help ?

**Comment by abhishek-jain-1999** [comment]
@srgothi92 Okay, sorry I thought updating on the [website](https://vcf2fhir.readthedocs.io/en/latest/) itself

**Comment by srgothi92** [comment]
Whenever we release new version, website will be updated too.
