### ISSUE TITLE
GitHub Action to build and publish Python package to PyPI

### ISSUE THREAD

**Issue by Rohan-cod** [elimuinformatics/vcf2fhir#60]
## Description

A GitHub Action to build and publish Python package to PyPI. **[This](https://github.com/marketplace/actions/py-package-publish)** GitHub Action by **[Mariam Maarouf](https://github.com/mariamrf)** or **[this](https://github.com/marketplace/actions/pypi-publish)** by **[Python Packaging Authority](https://github.com/pypa)** are some good candidates for this.

## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Package Version: Latest Version
* Operating System: Macintosh

**Comment by Rohan-cod** [comment]
@srgothi92, what are your thoughts on this? Should we add this to the repository?

**Comment by srgothi92** [comment]
I would prefer more controlled releases and time in release process is not that important because we don't do it very often.

**Comment by Rohan-cod** [comment]
Yes @srgothi92, that is also correct. In that case, I think I should close this issue. :)
