### ISSUE TITLE
Add genomic source class to variant observations

### ISSUE THREAD

**Issue by rhdolin** [elimuinformatics/vcf2fhir#63]
## Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

Consider allowing for inclusion of genomic source class (e.g. somatic vs. germline) via a new optional parameter. If specified, we would include an additional component in the variant observation. This component would have LOINC code 48002-0 'Genomic source class [Type]', with component values drawn from [here](https://loinc.org/LL378-1/).

## Current Behavior

We do not currently include genomic source class.

**Comment by VamakshiMagotra** [comment]
Hi Bob, I am a beginner looking for some good first issues. Can you please assign it to me?

**Comment by rhdolin** [comment]
Ok @VamakshiMagotra. Let me know if you need some guidance.

**Comment by rhdolin** [comment]
@VamakshiMagotra Apologies for the change in thinking, but I'm now thinking we should hold off on this one. We don't have a reliable way of knowing if a VCF is containing germline and/or somatic variants. This issue will need some more thought, so we should defer it for now.

**Comment by rhdolin** [comment]
This is being folded in to vcf2fhir for SV enhancements
