### ISSUE TITLE
Gene and disease description

### ISSUE THREAD

**Issue by apaytuvi** [elimuinformatics/vcf2fhir#9]
Dear authors of vcf2fhir,

We have genetic variants with VCF format. Your software is helping us to have the HL7 format, which our variants are included as `observations ` under `DiagnosticReport`. We also need to include the gene description (affected by some pathogenic variants) and the disease description caused by those affected genes. Nevertheless, vcf2fhir does not include this kind of information (we are trying to modify vcf2fhir in order to include this information) and we do not know where to put this information within the HL7 format. We think that including this information in each `observation` is wrong, since it will be redundant in case of many variants on the same gene. Do you have some feedback about it?

Thank you very much in advance.

**Comment by rhdolin** [comment]
Hi @apaytuvi . Thanks for writing. 

This first version of software focused on a direct translation from VCF to FHIR, with minimal supplemental annotations. We agree with the value of adding more annotations, and it's on the list of future enhancements. 

As for where they should go, I think we should remain aligned with the [HL7 Genomics Reporting Implementation Guide](http://build.fhir.org/ig/HL7/genomics-reporting/index.html). In the latest build, you'll see that the [variant observation](http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-variant.html) includes an optional 'gene-studied' component. I'd also suggest taking a look at the [diagnostic-implication profile](http://build.fhir.org/ig/HL7/genomics-reporting/StructureDefinition-diagnostic-implication.html) as the slot to put the disease. 

Just as an aside, the FHIR genomics workgroup has a discussion forum [here](https://chat.fhir.org/#narrow/stream/179197-genomics).
