### ISSUE TITLE
genetic variant assessment should be 'absent' when GT=0/0

### ISSUE THREAD

**Issue by Yun-00** [elimuinformatics/vcf2fhir#90]
Dear Authors of vcf2fhir,

In the current design of vcf2fhir, Observation-variant includes a fixed content 'LOINC 69548-6'. 
However, it would not be logical to convert the record this way when GT=0/0. 
Since GT=0/0 represents no variant occurs, the corresponding values of LOINC 69548-6 should be 'absent'.

## Prerequisites
- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed

## Context
* Package Version: vcf2fhir 0.0.17
* Operating System: Ubuntu 16.04.6 LTS

## Expected Behavior
When GT=0/0, the values of LOINC 69548-6 should be 'absent' (LA9634-2).

## Current Behavior
The value of LOINC 69548-6 is fixed. Always shows 'present' whenever the GT values are.

**Comment by Rohan-cod** [comment]
Hi @Yun-00, thanks for the issue. As per the current translation logic for **VCF** to **FHIR** conversion, we [exclude](https://github.com/elimuinformatics/vcf2fhir/blob/master/vcf2fhir/json_generator.py#L70) the vcf records where FORMAT.GT is in ['0/0', '0|0', '0']. You can find more about the exclusion criteria under the **Exclusions** section [here](https://docs.google.com/document/u/1/d/1NSKsT44b1N_alrP_T0DRaTANGg-G0Yx5jNfGaYGUvFY/)

**Comment by Yun-00** [comment]
Hi @Rohan-cod , Thanks for replying. Maybe i should switch to the current version. Appreciate your great work.

**Comment by Rohan-cod** [comment]
> Hi @Rohan-cod , Thanks for replying. 

No problem. :)

> Appreciate your great work.

Thanks @Yun-00. 😇
